# TODO: Choose a base image (e.g., python:3.11-slim)

# TODO: Set the working directory inside the container

# TODO: Copy the dependency file first (for layer caching)

# TODO: Install uv and sync dependencies

# TODO: Copy the rest of the project files

# TODO: Set the default command to run the full pipeline
